---
# Items that apply to all profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/


# Clustered Eureka server
---
spring:
  profiles: clustered
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/


# Word servers
---
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: article
words: a,the

---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog

---
spring:
  profiles: subject
words: I,You,He,She,It
  
---
spring:
  profiles: verb
words: ran,knew,had,saw,bought
